<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="manual.xsl"?>
<!DOCTYPE document [
        <!ELEMENT document (title, item+)>
        <!ELEMENT item ((item? | (heading?, (section? | text?)))+)>
        <!ELEMENT section ((item | text))+>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT table (tr)+>
        <!ELEMENT tr (th|td)+>
        <!ELEMENT th (#PCDATA)>
        <!ELEMENT td (#PCDATA|a|b|br|code|note)*>
        <!ELEMENT br (#PCDATA)>
        <!ELEMENT var (#PCDATA)>
        <!ELEMENT code (#PCDATA|var)*>
        <!ELEMENT note (#PCDATA|a|var|code)*>
        <!ELEMENT img (#PCDATA)>
        <!ELEMENT imgThumb (#PCDATA)>
        <!ELEMENT a (#PCDATA)>
        <!ELEMENT text (#PCDATA|table|a|ul|ol|br|var|code|note|img|imgThumb)*>
        <!ELEMENT b (#PCDATA)>
        <!ELEMENT ul (li)+>
        <!ELEMENT ol (li)+>
        <!ELEMENT li (#PCDATA|a|var)*>
        <!ATTLIST heading id ID #REQUIRED>
        <!ATTLIST a href CDATA #IMPLIED>
        <!ATTLIST a target CDATA #IMPLIED>
        <!ATTLIST img src CDATA #REQUIRED>
        <!ATTLIST table class CDATA #IMPLIED>
        <!ATTLIST td class CDATA #IMPLIED>
        <!ATTLIST td nowrap CDATA #IMPLIED>
        <!ATTLIST imgThumb src CDATA #REQUIRED>
        <!ATTLIST imgThumb alt CDATA #IMPLIED>
        <!ATTLIST imgThumb width CDATA #IMPLIED>
        ]>
<document>
    <title>JSCover User Manual</title>
    <item>
        <heading id="generalInformation">General Information</heading>
        <section>
            <text>
                This document should now be complete and accurate, however, please feel free to consult the
                <a href="http://siliconforks.com/jscoverage/manual.html" target="_blank">JSCoverage documentation</a>.
            </text>
            <item>
                <heading id="introduction">Introduction</heading>
                <text>
                    JSCover is a tool that measures code coverage for JavaScript programs.
                    It is based on the popular JSCoverage, with the C++/SpiderMonkey instrumentation replaced with
                    Java/Closure-Compiler.
                </text>
                <text>
                    JSCover works by adding instrumentation to JavaScript code before it is executed in a web browser.
                    JSCover provides several alternative ways of doing this:
                    <ul>
                        <li>The simplest method is to use the server mode, a simple web server that instruments
                            JavaScript code as it is served.
                        </li>
                        <li>Alternatively, you can use the file-system mode program to generate instrumented JavaScript
                            files.
                        </li>
                        <li>Finally, the server mode can be run with the --proxy option to act as a proxy server which
                            instruments any JavaScript code proxied through it.
                        </li>
                    </ul>
                </text>
            </item>
            <item>
                <heading id="packaging">Packaging</heading>
                <text>
                    JSCover comes packaged in two JARs.
                    The first option is preferred to avoid class-path issues, especially as JSCover may be using a
                    different version of the Closure-Compiler to your build.
                </text>
                <text>
                    <ul>
                        <li>
                            JSCover-all.jar
                            which includes all dependencies
                        </li>
                        <li>
                            JSCover.jar
                            which must have all dependent JARs available in the same directory
                        </li>
                    </ul>
                </text>
                <text>
                    The JARs are available in the ZIP download file under the directory <var>target/dist</var>
                </text>
                <text>
                    The maven release includes the <var>JSCover.jar</var> JAR with dependencies managed by Maven.
                </text>
            </item>
            <item>
                <heading id="mavenPlugin">Maven Plugin</heading>
                <text>
                    There is a maven plugin for JSCover available. See the
                    <a href="https://github.com/tntim96/JSCover-maven-plugin" target="_blank">JSCover-maven-plugin</a>
                    project.
                </text>
                <text>
                    This is now functional and currently being enhanced.
                </text>
            </item>
        </section>
    </item>
    <item>
        <heading id="gettingStarted">Getting started</heading>
        <text>
            <note>
                While these examples use iframes, this can be avoided by using the
                <a href="#localStorage">HTML5 localStorage</a> switch.
            </note>
        </text>
        <section>
            <item>
                <text>The best way to get started is to run the examples included in the distribution.</text>
                <heading id="gettingStartedServer">Server</heading>
                <item>
                    <heading id="gettingStartedServerStartServer">Start The Server</heading>
                    <text>
                        Run&#160;<var>jscover-server.bat</var>&#160;or&#160;<var>jscover-server.sh</var>. The contents
                        are:
                        <code>java -jar target/dist/JSCover-all.jar -ws --document-root=doc/example --report-dir=target</code>
                        This will start a web server, and the JSCover interface can be loaded by going to
                        <a href="http://localhost:8080/jscoverage.html">http://localhost:8080/jscoverage.html</a>.
                        <br/>
                        <imgThumb src="images/ws-1-browser.png" alt="Load JSCover" width="650"/>
                        <br/>
                        You can then enter the URL
                        <var>http://localhost:8080/index.html</var>
                        in the URL input box and click on the
                        <var>Open in frame</var>
                        button.
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedServerLoadURL">Load The Test Page</heading>
                    <text>
                        To automatically load the web-page without entering it in the URL section, got to
                        <a href="http://localhost:8080/jscoverage.html?index.html">http://localhost:8080/jscoverage.html?index.html</a>.
                        <br/>
                        <imgThumb src="images/ws-2-browser.png" alt="Load Test Page" width="650"/>
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedServerRunTests">Run Tests</heading>
                    <text>
                        Tests that exercise the JavaScript can now be run.
                        <note>The coverage report statistics are cumulative unless you reload the jscoverage.html
						page without using the
							<a href="#localStorage">localStorage switch</a>).</note>
                        <imgThumb src="images/ws-3-browser.png" alt="Run Tests" width="650"/>
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedServerCoverageSummary">View The Coverage Summary</heading>
                    <text>
                        To see a summary of the coverage, click the
                        <var>Summary</var>
                        tab. Note, you can change the sorting
                        order by clicking on the
                        <var>File</var>,
                        <var>Coverage</var>,
                        <var>Branch</var>
                        or
                        <var>Function</var>
                        links:
                        <br/>
                        <imgThumb src="images/ws-4-summary.png" alt="Coverage Summary" width="650"/>
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedServerUncoveredLines">View Uncovered Lines</heading>
                    <text>
                        To see uncovered lines, check the
                        <var>Show missing statements column</var>
                        check-box:
                        <br/>
                        <imgThumb src="images/ws-5-summary.png" alt="Uncovered Lines" width="650"/>
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedServerViewSource">View The Source</heading>
                    <text>
                        To view the source, click on the script-name link in the
                        <var>File</var>
                        column (shown above) - the
                        result is shown below.
                        <br/>
                        <imgThumb src="images/ws-6-source.png" alt="View Source" width="650"/>
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedServerViewUncoveredBranch">View Uncovered Branches</heading>
                    <text>
                        To determine which branch path was not covered click on the
                        <var>info</var>
                        link.
                        <br/>
                        <imgThumb src="images/ws-7-source.png" alt="Uncovered Branches" width="650"/>
                    </text>
                    <text>
                        If there are multiple paths, for example:
                        <code>if (code !== undefined &amp;&amp; code !== null &amp;&amp; code !== '') {</code>
                        The uncovered information may be:
                        <br/>
                        <img src="images/ws-8-source.png"/>
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedServerReportStorage">Store The Report</heading>
                    <text>
                        To store the report, click on the
                        <var>Store</var>
                        tab and then the
                        <var>Store Report</var>
                        button.
                        <br/>
                        <imgThumb src="images/ws-9-store.png" alt="Store Report" width="650"/>
                        <br/>
                        <note>The report does not work in Google Chrome when viewed using a file: URL. Either use an
                            ordinary web server to serve the report (JSCover comes with a
                            <a href="#simpleWebServer">simple web server</a>) or start Google Chrome with the
                            <var>--allow-file-access-from-files</var>
                            command line option.
                        </note>
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedServerStop">Stop The Server</heading>
                    <text>
                        To stop the server, click on the
                        <var>Store</var>
                        tab and then the
                        <var>Stop Server</var>
                        button.
                        <br/>
                        <imgThumb src="images/ws-10-stop.png" alt="Stop Server" width="650"/>
                    </text>
                    <text>
                        Alternatively, the server can be stopped by entering the URI path
                        <var>/stop</var> (for example <var>http://localhost:8080/stop</var>).
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedServerAbout">About Page</heading>
                    <text>
                        Version and other information can be viewed by clicking on the
                        <var>About</var>
                        tab:
                        <br/>
                        <img src="images/ws-11-about.png"/>
                    </text>
                </item>
            </item>
            <item>
                <heading id="gettingStartedProxy">Proxy</heading>
                <text>
                    The proxy mode operates in a similar fashion to the server.
                    To demonstrate the proxy functionality locally, perform the following steps or
                    see <a href="#automatingWebDriverProxy">here</a> for a working web-driver example.
                </text>
                <item>
                    <heading id="gettingStartedProxyHost">Edit Your Hosts File</heading>
                    <text>
                        Edit your host file adding the following entry
                        <code>127.0.0.1       localhost-proxy</code>
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedProxyBrowser">Configure Browser To Use The Proxy</heading>
                    <text>
                        Set the proxy-host to <var>localhost</var>
                        and the proxy-port to <var>3128</var>.
                        Make sure 'localhost' is in the proxy-bypass list, and that 'localhost-proxy' is not.
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedProxyWS">Start A Web-Server</heading>
                    <text>
                        This is the web-server we'll be accessing via the proxy.
                        Run
                        <var>web-server.bat</var>
                        or
                        <var>web-server.sh</var>. The contents are:
                        <code>java -cp target/dist/JSCover-all.jar jscover.server.SimpleWebServer . 8080</code>
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedProxyProxy">Start JSCover as a proxy</heading>
                    <text>
                        Run
                        <var>jscover-proxy.bat</var>
                        or
                        <var>jscover-proxy.sh</var>. The contents are:
                        <code>$ java -jar target/dist/JSCover-all.jar -ws --proxy --port=3128 --report-dir=target</code>
                    </text>
                    <text>
                        Point your browser to:
                        <a href="http://localhost-proxy:8080/jscoverage.html?doc/example/index.html">http://localhost-proxy:8080/jscoverage.html?doc/example/index.html</a>.
                    </text>
                    <text>
                        The site can now be instrumented in a similar way to the server mode in the previous section.
                    </text>
                </item>
                <item>
                    <heading id="gettingStartedProxySave">Save the report in proxy mode</heading>
                    <text>
                        If you loaded your site in the proxy i-frame, you can use the JSCover UI to save the report.
                    </text>
                    <text>
                        If you are using <code>--local-storage</code> without i-frames, you can point your browser to:
                        <a href="http://localhost-proxy:8080/jscoverage.html">http://localhost-proxy:8080/jscoverage.html</a>
                        and save the report via the JSCover UI.
                    </text>
                </item>
            </item>
            <item>
                <heading id="gettingStartedFileSystem">File System</heading>
                <text>
                    Run
                    <var>jscover-filesystem.bat</var>
                    or
                    <var>jscover-filesystem.sh</var>. The contents are:
                    <code>java -jar target/dist/JSCover-all.jar -fs doc/example target/example</code>
                    This will recursively copy all the resources from
                    <var>doc/example</var>
                    to
                    <var>target/example</var>,
                    and create the JSCover files (e.g. jscoverage.html) at
                    <var>target/example</var>.
                </text>
                <text>
                    This can either be via the file-system,
                    <note>but is not recommended due to
                        <a href="http://code.google.com/p/chromium/issues/detail?id=4197">security restrictions</a>
                    </note>
                    .
                    You would enter something like the following in your address bar:
                    <var>file:///C:/Java/JSCover/target/example/jscoverage.html?index.html</var>
                    <br/>
                    <imgThumb src="images/fs-1-file-system.png" alt="File System" width="650"/>
                </text>
                <item>
                    <heading id="fileSystemSave">Store The Report</heading>
                    <item>
                        <heading id="fileSystemJSON">Save The Coverage JSON</heading>
                        <text>
                            The file-system mode web-UI does not have a <var>Store Report</var> button, however the
                            report can still be saved to the file-system. The JSON for the report can be generated by
                            calling the <var>jscoverage_serializeCoverageToJSON()</var> function.
                        </text>
                        <text>
                            WebDriver
                            <code>String json = (String)((JavascriptExecutor) webClient).executeScript("return jscoverage_serializeCoverageToJSON();");</code>
                        </text>
                        <text>
                            Selenium
                            <code>String json = selenium.getEval("selenium.browserbot.getUserWindow().jscoverage_serializeCoverageToJSON();");</code>
                        </text>
                        <text>
                            HtmlUnit
                            <code>String json = (String)((ScriptResult)((HtmlPage)webWindow.getEnclosedPage()).
                                executeJavaScript("jscoverage_serializeCoverageToJSON();")).getJavaScriptResult();</code>
                        </text>
                        <text>
                        PhantomJS
<code>var json = page.evaluate(function(){
    return jscoverage_serializeCoverageToJSON();
});
fs.write("target/jscoverage.json", json, 'w');
</code>
                            Find a working example in the <var>examples/phantomJS-file-system</var>
                            directory of the distribution.
                        </text>
                        <text>
                            Once the JSON is available in your browser driver, it can then be saved to the file-system
                            using that environment's file-system API. The JSCover report files (and optionally the
                            original JavaScript source) can be generated with the <var>-gf</var> option.
                            See the examples/phantomJS-file-system example.
                        </text>
                    </item>
                    <item>
                        <heading id="fileSystemJSCoverUI">Enable JSCover Web UI</heading>
                        <text>
                            If you want to view the report using JSCover's web-UI, you can generate the other report
                            files (jscoverage.js, jscoverage.html, jscoverage.css, jscoverage-highlight.css,
                            jscoverage-ie.css, jscoverage-throbber.gif) in server mode.
                            <note>The <var>jscoverage.js</var> file generated in server mode has the code
                                <code>jscoverage_isReport = true;</code> at the end which is required to view the
                                stored report.</note>
                        </text>
                    </item>
                </item>
            </item>
            <item>
            <heading id="simpleWebServer">Non-Instrumenting Web Server</heading>
                <text>
                    To avoid any file-system issues (described above),
                    JSCover comes with a simple non-instrumenting web server.
                    Run it from the distribution's root directory:
                    <code>java -cp target/dist/JSCover-all.jar jscover.server.SimpleWebServer . 8080</code>
                    Then point your browser at:
                    <a href="http://localhost:8080/doc/example-qunit/out/jscoverage.html?test/index.html"
                            >http://localhost:8080/doc/example-qunit/out/jscoverage.html?test/index.html</a>
                    The UI interaction should now be the same as for the server except for the missing
                    <var>Store</var>
                    tab.
                </text>
            </item>
        </section>
    </item>
    <item>
        <heading id="usage">Usage</heading>
        <section>
            <item>
                <heading id="usageGeneral">General</heading>
                <text>
                    <code>java -jar JSCover-all.jar [OPTIONS]...</code>
                    <code>java -jar JSCover.jar [OPTIONS]...</code>
                </text>
                <text>
                    Command line options are:
                </text>
                <text>
                    <table>
                        <tr>
                            <th>Option</th>
                            <th>Default</th>
                            <th>Description</th>
                        </tr>
                        <tr>
                            <td>-ws</td>
                            <td>N/A</td>
                            <td>Run in&#160;<b>w</b>eb&#160;<b>s</b>erver mode - see
                                <a href="#serverMode">below</a>
                            </td>
                        </tr>
                        <tr>
                            <td>-fs</td>
                            <td>N/A</td>
                            <td>Run in&#160;<b>f</b>ile&#160;<b>s</b>ystem mode - see
                                <a href="#fileMode">below</a>
                            </td>
                        </tr>
                        <tr>
                            <td>-io</td>
                            <td>N/A</td>
                            <td>Instrument single file to instrument single file to stdout <b>I/O</b> stream</td>
                        </tr>
                        <tr>
                            <td>-gf [SRC] DEST</td>
                            <td>N/A</td>
                            <td>
                                Generate JSCover report files to DEST.
                                Optionally copy JavaScript files from SRC to DEST/original-src
                            </td>
                        </tr>
                        <tr>
                            <td>-regex-test REGEX STRING</td>
                            <td>N/A</td>
                            <td>Test of regular expression (REGEX) matches string (STRING)</td>
                        </tr>
                        <tr>
                            <td>-h,--help</td>
                            <td>N/A</td>
                            <td>Display command line help</td>
                        </tr>
                        <tr>
                            <td>-h encoding</td>
                            <td>N/A</td>
                            <td>List available character encodings</td>
                        </tr>
                        <tr>
                            <td>-V,--version</td>
                            <td>N/A</td>
                            <td>Display version</td>
                        </tr>
                    </table>
                </text>
                <item>
                    <heading id="encoding">Encoding</heading>
                    <text>
                        The encoding defaults to the platform's default encoding which is usually what you want.
                        To specify an encoding, add the JVM option
                        <var>-Dfile.encoding=ENCODING</var>.
                        For example:
                        <code>java -Dfile.encoding=UTF-8 -jar JSCover-all.jar [OPTIONS]...</code>
                        <note>To see the available encodings (as well as the current default) run
                            <var>JSCover</var>
                            with options
                            <var>-h encoding</var>
                        </note>
                        <code>java -jar JSCover-all.jar -h encoding</code>
                    </text>
                </item>
                <item>
                    <heading id="enableAssertions">Enable Assertions</heading>
                    <text>
                        To help detect errors while running JSCover, run the JVM with assertions enabled
                        (JVM flag <var>-ea</var>).
                        For example:
                        <code>java -ea -jar JSCover-all.jar -ws --port=80 --no-instrument=lib --no-instrument=test</code>
                    </text>
                </item>
                <item>
                    <heading id="jvmRegularExpressions">Java Regular Expressions</heading>
                    <text>
                        All regular expression functionality is provided by the JVM.
                        Regular expressions can be tested with the '-regex-test' switch. For example:
                        <code>java -jar JSCover-all.jar -regex-test "/a.*" "/ab"</code>
                    </text>
                    <text>
                        Further documentation can be found at:
                        <ul>
                            <li><a href="https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html" target="_blank">Pattern</a></li>
                            <li><a href="https://docs.oracle.com/javase/8/docs/api/java/util/regex/Matcher.html" target="_blank">Matcher</a></li>
                        </ul>
                    </text>
                </item>
                <item>
                    <heading id="exitStatus">Program Exit Status</heading>
                    <text>
                        If any exceptions were thrown, the program will exit with an exit status of 1.
                    </text>
                </item>
            </item>
            <item>
                <heading id="serverMode">Server Mode</heading>
                <text>
                    <code>java -jar JSCover-all.jar -ws [OPTIONS]</code>
                    For example:
                    <code>java -jar JSCover-all.jar -ws --port=80 --no-instrument=lib --no-instrument=test</code>
                </text>
                <text>
                    <table>
                        <tr>
                            <th>Option</th>
                            <th>Default</th>
                            <th>Description</th>
                        </tr>
                        <tr>
                            <td>-h,--help</td>
                            <td>N/A</td>
                            <td>Display command line help</td>
                        </tr>
                        <tr>
                            <td>--document-root=PATH</td>
                            <td>current directory</td>
                            <td>Serve web content from the directory given by PATH (can be relative or absolute)</td>
                        </tr>
                        <tr>
                            <td>--no-instrument=URL</td>
                            <td>None</td>
                            <td>Specify URLs not to be instrumented. Can be specified multiple times.</td>
                        </tr>
                        <tr>
                            <td>--no-instrument-reg=URL</td>
                            <td>None</td>
                            <td>
                                Same as '--no-instrument=PATH', except PATH is interpreted as a
                                <a href="#jvmRegularExpressions">regular expression</a>
                            </td>
                        </tr>
                        <tr>
                            <td nowrap="nowrap">--only-instrument-reg=URL</td>
                            <td>None</td>
                            <td>
                                Changes the default behavior to skip instrumentation except for the specified URLs
                                matching the <a href="#jvmRegularExpressions">regular expression</a>.
                                This switch can be overridden if no-instrument switches are specified first.
                            </td>
                        </tr>
                        <tr>
                            <td>--report-dir=PATH</td>